import XCTest

/// The end-to-end leg for the editor's link policy: a link annotation
/// inside an imported document is not followed when tapped.
///
/// Route: `--loadTestDocument --linkDoc` opens the one-page synthetic
/// fixture (UITestFixtures/uitest_link.pdf, generated by
/// Scripts/generate_uitest_link.py) whose single `/Link` annotation
/// covers the page's central band with a URI under the reserved
/// `.invalid` domain. A tap at the page's center lands on it. The leg
/// taps once with the drawing tool off and once with the Rectangle tool
/// on (a plain tap is not a drag, so the overlay does not consume it),
/// and after each tap asserts that this app is still the foreground
/// application and that Safari is not — PDFKit's default without a
/// delegate is to open the annotation's URL in the system browser.
///
/// Rails: the tap is a window-normalized coordinate press (the served
/// editor element's frame is used when it is available, the window
/// otherwise); the settle wait after the tap is generous because an
/// injected touch can land late on a loaded host. Safari's state is read
/// through `XCUIApplication(bundleIdentifier:)`, which reports another
/// app's process state without launching it.
///
/// Runs in the simulator suite census, not the pull-request gate (no
/// XCUI there). Cost class: one fixture load, two taps.
///
/// nonisolated for the same reason as the sibling suites: an XCUITest
/// drives a separate process and touches no @MainActor app state.
nonisolated final class DocumentLinkUITests: XCTestCase {

    private var app: XCUIApplication!

    override func setUp() {
        super.setUp()
        continueAfterFailure = false
        app = XCUIApplication()
    }

    override func tearDown() {
        app = nil
        super.tearDown()
    }

    func testLinkAnnotationTap_toolOffAndOn_appStaysForegroundAndSafariDoesNotLaunch() {
        app.launchArguments = ["--uitesting", "--loadTestDocument", "--linkDoc"]
        app.launch()

        XCTAssertTrue(
            app.buttons["drawTool"].waitForExistence(timeout: 30),
            "The editor's Rectangle tool never appeared — check the --linkDoc launch hook."
        )
        // The editor group is labelled with the page count; the link
        // fixture is one page. (The page's text is not served as static
        // text, so the fixture is identified by its route and the
        // attached frame.)
        XCTAssertTrue(
            app.otherElements
                .matching(NSPredicate(format: "label == 'Document editor, page 1 of 1'"))
                .firstMatch
                .waitForExistence(timeout: 15),
            "The editor never reported a one-page document — the link fixture did not open."
        )
        attachScreenshot(named: "documentlink-00-editor")

        // Arm 1: drawing tool off.
        tapPageCenter()
        assertAppStaysInFront(arm: "drawing tool off")
        attachScreenshot(named: "documentlink-01-after-tap-tool-off")

        // Arm 2: Rectangle tool on.
        enterDrawMode()
        tapPageCenter()
        assertAppStaysInFront(arm: "Rectangle tool on")
        attachScreenshot(named: "documentlink-02-after-tap-tool-on")
    }

    // MARK: - Helpers

    /// The document editor element (labelled "Document editor, page N of
    /// M") when it is served; otherwise the window. Both center on the
    /// page at fit for a one-page Letter fixture on this device class.
    private var pageSurface: XCUIElement {
        let editor = app.otherElements
            .matching(NSPredicate(format: "label BEGINSWITH 'Document editor'"))
            .firstMatch
        if editor.waitForExistence(timeout: 5), editor.frame.height > 100 {
            return editor
        }
        return app.windows.firstMatch
    }

    private func tapPageCenter() {
        pageSurface
            .coordinate(withNormalizedOffset: CGVector(dx: 0.5, dy: 0.5))
            .tap()
    }

    /// After a link tap this app must still be the foreground application
    /// and Safari must not be. The settle wait gives a late-landing touch
    /// and a would-be app switch time to show.
    private func assertAppStaysInFront(arm: String) {
        Thread.sleep(forTimeInterval: 2)
        let safari = XCUIApplication(bundleIdentifier: "com.apple.mobilesafari")
        XCTAssertEqual(
            app.state, .runningForeground,
            "After tapping the link annotation with the \(arm), the app left the foreground."
        )
        XCTAssertNotEqual(
            safari.state, .runningForeground,
            "After tapping the link annotation with the \(arm), Safari came to the foreground."
        )
    }

    private func enterDrawMode() {
        let tool = app.buttons["drawTool"]
        XCTAssertTrue(tool.waitForExistence(timeout: 10), "Rectangle tool not present.")
        for _ in 0..<3 {
            tool.tap()
            if waitForToolValue("Drawing mode active", timeout: 6) { return }
        }
        XCTFail("The Rectangle tool did not report drawing mode after three taps.")
    }

    private func waitForToolValue(_ expected: String, timeout: TimeInterval = 10) -> Bool {
        let tool = app.buttons["drawTool"]
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if (tool.value as? String) == expected { return true }
            usleep(250_000)
        }
        return (tool.value as? String) == expected
    }

    private func attachScreenshot(named name: String) {
        let shot = XCTAttachment(screenshot: app.screenshot())
        shot.name = name
        shot.lifetime = .keepAlways
        add(shot)
    }
}
